config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    get 'drafts', on: :collection
    get 'search', on: :collection
  end 

resources :users
get '/signup', to: 'users#new'

root :to => 'welcome#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  def self.ordered_first_10
    order("published_at").limit(10)
  end

  # It returns the posts whose titles contain one or more words that form the query
  def self.search(query)
    # where(:subject, query) -> This would return an exact match of the query
    # where("subject like ?", "%#{query}%")
    where("subject LIKE :query OR body LIKE :query", query: "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Add save handlers for formatting data
	before_create :create_remember_token
	before_save :normalize_fields

	# Validates name:
	validates :name,
		presence: true,
		length: {maximum: 50}

	# Validates email:
	validates :email,
		presence: true,
		uniqueness: {case_sensitive: false},
	format: {with: /[^@]+@[^@]+/ }
	# Alternative method
	# format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

	# Validates password length
	validates :password,
		length: {minimum: 8 }

	# Secure password features:
	has_secure_password

	# attr_accessible :email, :password, :password_confirmation

	# validates_uniqueness_of :email

	# Create a new remember token for the user:
	def self.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def self.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	# Creates new sessions token for the user
	def create_remember_token
		remember_token = User.hash(User.new_remember_token)
	end

	# Normalize fields for consistancy
	def normalize_fields
		self.email.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.ordered_first_10
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:subject, :body, :published_at) #, :draft_status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to @user
      # redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def users_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- When submit the form, the view rendered will be the index view of our posts resource -->
  <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Posts" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn" type="submit">Search<i class="icon-search"></i></button>
    </div>
  <% end %>

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>
<hr class="header"></hr>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_local_field :published_at %>
  </div>
  <!-- <div class="field">
    <%# f.label :draft_status %><br>
    <%# f.check_box :draft_status %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="top_right">
<%= link_to "<button>Show</button>".html_safe, @post %>
<%= link_to "<button>New Post</button>".html_safe, new_post_path %>
<%= link_to "<button>Join Us</button>".html_safe, users_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="top_right">
<%= link_to "<button>New Post</button>".html_safe, new_post_path %>
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Join Us</button>".html_safe, users_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<h1>Listing posts</h1>
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Publish Date</th>
      <!-- <th>Draft Status</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% if @posts.empty? %>
      <td class="noposts">No Posts available</td>
    <% else %>

    <% @posts.each do |post| %>
      <tr>
        <td><%= post.subject %></td>
        <td><%= post.body %></td>
        <td><%= post.published_at %></td>
        <td><%# post.draft_status %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

app/views/posts/new.html.erb
<div class="top_right">
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Join Us</button>".html_safe, users_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="top_right">
<%= link_to "<button>Edit</button>".html_safe,edit_post_path(@post) %>
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Join Us</button>".html_safe, users_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Publish Date:</strong>
  <%= @post.published_at %>
</p>

<!-- <p>
  <strong>Draft Status:</strong>
  <%# @post.draft_status %>
</p> -->

app/views/users/edit.html.erb
<div class="top_right">
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Back</button>".html_safe, users_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

app/views/users/index.html.erb
<div class="top_right">
<%= link_to "<button>Sign Up</button>".html_safe, new_user_path %>
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<h1>Thank you for your intrest, sign up now!</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="top_right">
<%= link_to "<button>Back</button>".html_safe, users_path %>
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <%= @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>
  <br>
   <%= f.label :email %>
   <%= f.text_field :email %>
  <br>
   <%= f.label :password %>
   <%= f.password_field :password %>
  <br>
   <%= f.label :password_confirmation, 'Confirm Password' %>
   <%= f.password_field :password_confirmation %>
  <br>
   <%= f.submit 'Submit', id: 'submit' %>
 <% end %>

app/views/users/show.html.erb
<div class="top_right">
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Home</button>".html_safe, root_path %>
</div>

<h1> Thanks for joining!</h1>

app/views/welcome/home.html.erb
<div class="top_right">
<%= link_to "<button>Post Page</button>".html_safe, posts_path %>
<%= link_to "<button>Join Us</button>".html_safe, users_path %>
</div>

<h1> Welcome to my Blog </h1>